config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products do
    get :who_bought, on: :member
  end
  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-custom">
  <div class="container-fluid d-inline-flex">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      <a class="navbar-brand justify-cotent-start" href="#">Main</a>
    </button>
    <a class="navbar-brand justify-cotent-start" href="/">Home</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto d-md-flex">
        <% if session[:user_id] %>
          <li class="nav-item"><a class="nav-link" href="<%= orders_path %>">Orders</a></li>
          <li class="nav-item"><a class="nav-link" href="<%= products_path %>">Products</a></li>
          <li class="nav-item"><a class="nav-link" href="<%= users_path %>">Users</a></li>
          <li class="nav-item"><a class="nav-link" data-method="delete" href="<%= logout_path %>">Logout</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>